// order Book
export const UPDATE_ORDER_BOOK = 'UPDATE_ORDER_BOOK';
// order Form
export const UPDATE_ORDER_FORM_TAB = 'UPDATE_ORDER_FORM_TAB';
export const UPDATE_ORDER_FORM_EXCHANGE = 'UPDATE_ORDER_FORM_EXCHANGE';
export const UPDATE_ORDER_FORM = 'UPDATE_ORDER_FORM';
export const TOGGLE_BUY_SELL_ORDER_FORM = 'TOGGLE_BUY_SELL_ORDER_FORM';
// transaction history
export const UPDATE_TRADE_HISTORY = 'UPDATE_TRADE_HISTORY';
