// order Book
export const UPDATE_ORDER_BOOK = 'UPDATE_ORDER_BOOK';
// order Form
export const UPDATE_ORDER_FORM_TAB = 'UPDATE_ORDER_FORM_TAB';
export const UPDATE_ORDER_FORM_EXCHANGE = 'UPDATE_ORDER_FORM_EXCHANGE';
export const UPDATE_ORDER_FORM = 'UPDATE_ORDER_FORM';

